language: python
python:
  - "2.6"
before_install:
  - sudo apt-get install texlive-math-extra dvipng texlive-latex-extra python-sphinx python-argparse python-dateutil python-tz
  - sudo easy_install -U dateutils
script: 
  - cd blogweb && sudo make html
